active_llm_config: glm_default
chunking:
  chunk_length: 512
  language: zh
  ppl_threshold: 0.3
  strategy: meta_ppl
data:
  data_location: ./data/upload/20250628
glm:
  api_key: 
  model_name: glm-4.5-flash
llm_configs:
  glm_default:
    api_endpoint: https://open.bigmodel.cn/api/paas/v4/chat/completions
    api_key: 
    model_name: glm-4.5-flash
    provider: zhipu
milvus:
  collection_name: Test_one
  host: 127.0.0.1
  index_device: cpu
  index_name: IVF_FLAT
  port: '19530'
  replica_num: 1
  vector_name: default
multimodal:
  clip_model: ViT-B/32
  enable_image: false
  image_formats:
  - jpg
  - jpeg
  - png
  - bmp
performance:
  enable_custom_metrics: true
  max_history: 1000
  monitor_interval: 1.0
search:
  col_choice: hdbscan
  reorder_strategy: distance
  top_k: 29
system:
  insert_mode: overwrite
  url_split: false
testing:
  enable_performance_test: true
  locust_config:
    run_time: 60s
    spawn_rate: 1
    users: 10
  test_collection_name: locust_test_collection
  test_data_size: 10000
